<center><font class="error">Este sistema de ayuda está bajo construcción. 
Se agregarán más secciones en la próximas actualizaciones. <br>
<br>Última actualización: 16/12/2005.</font></center>
<h1>Contenido:</h1>
<ol>
  <li><a href="../locale/es/help/COI_MANUAL DE PROCEDIMIENTOS.pdf">Manual de procedimientos</a></li>
  <li><a href="../locale/es/help/COI_MANUALES_V1_html.htm">Manual de usuario</a></li>	
  <li><a href="../shared/help.php?page=status">Comprendiendo estados de cambios de bibliografía</a></li>
  <li>Ayuda de nivel de página</li>
    <ol type="a">
      <li><a href="../shared/help.php?page=biblioEdit">Nueva bibliografía y páginas de editar (Editar-Básica)</li>
    </ol>
  
</ol>
