<h1>Comprendiendo estados de cambios de bibliografía:</h1>
La siguiente tabla lista los posibles estados de un ejemplar.<br><br>
<table class="primary">
  <tr><th>Estado</th><th>Descripción</th></tr>
  <tr><td class="primary" valign="top">Disponible</td><td class="primary">La bibliografía es archivada y disponible para préstamos.</td></tr>
  <tr><td class="primary" valign="top">Prestado</td><td class="primary">La bibliografía ha sido prestada a un socio de la biblioteca.</td></tr>
  <tr><td class="primary" valign="top">Reservado</td><td class="primary">La bilbiografía es reservada para el socio que se encuentra en la lista de espera de un ejemplar. </td></tr>
  <tr><td class="primary" valign="top">Carrito de reposición en estantería</td><td class="primary">La bilbiografía se encuentra en el carrito de reposición a la espera de ser archivada en la estantería.</td></tr>
  <tr><td class="primary" valign="top">Dañado/En reparación</td><td class="primary">La bibliografía está siendo reparada debido a que presentaba daños.</td></tr>
  <tr><td class="primary" valign="top">Zona de visualización</td><td class="primary">La bibliografía no está disponible para préstamos porque se encuentra en zona de visualización.</td></tr>
  <tr><td class="primary" valign="top">Perdido/Extraviado</td><td class="primary">La bibliografía no está disponible para préstamos porque se encuentra extraviada.</td></tr>
  <tr><td class="primary" valign="top">on loan?</td><td class="primary">Bibliography is on loan.?</td></tr>
  <tr><td class="primary" valign="top">En pedido</td><td class="primary">La bibliografía está en pedido y aún no ha llegado.</td></tr>
</table>
<br>
Los cambios de estados de la bibliografía que son permitidos bajo las siguientes reglas.<br><br>
<table class="primary">
  <tr><th>Página</th><th>Estado antiguo</th><th>Estado nuevo</th><th>Reglas</th></tr>
  <tr>
    <td class="primary" valign="top" rowspan="3">Información del socio</td>
    <td class="primary" valign="top">Disponible</td>
    <td class="primary" valign="top">Prestado</td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top">Prestado</td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Reservado</td>
    <td class="primary" valign="top">Prestado</td>
    <td class="primary" valign="top">Permitido solo si el  socio es el primero en la cola de espera para el ejemplar o si la cola está vacía.</td>
  </tr>
  <tr>
    <td class="primary" valign="top" rowspan="5">Disponibilidades</td>
    <td class="primary" valign="top">Prestado</td>
    <td class="primary" valign="top">Carrito de reposición en estantería</td>
    <td class="primary" valign="top">Puede calcular las últimas multas.</td>
  </tr>
  <tr>
    <td class="primary" valign="top">Prestado</td>
    <td class="primary" valign="top">Reservado</td>
    <td class="primary" valign="top">Puede calcular las últimas multas y mostrar un mensaje para colocar el libro en el lugar donde se almacena.</td>
  </tr>
  <tr>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top">Carrito de reposición en estantería</td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Reservado</td>
    <td class="primary" valign="top">Carrito de reposición en estantería</td>
    <td class="primary" valign="top">Permitido solo si la cola de espera para un ejemplar está vacía.</td>
  </tr>
  <tr>
    <td class="primary" valign="top">Carrito de reposición en estantería</td>
    <td class="primary" valign="top">Disponible</td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top" rowspan="5">Información de la bibliografía</td>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top">Disponible</td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Disponible</td>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top"></td>
  </tr>
  <tr>
    <td class="primary" valign="top">Reservado</td>
    <td class="primary" valign="top">Disponible</td>
    <td class="primary" valign="top">Permitido solo si la cola de espera para un ejemplar está vacía.</td>
  </tr>
  <tr>
    <td class="primary" valign="top">Reservado</td>
    <td class="primary" valign="top">Otro<sup>*</sup></td>
    <td class="primary" valign="top">Permitido solo si la cola de espera para un ejemplar está vacía.</td>
  </tr>
</table>

<font class="small">* - nota: "otro" incluye los estados: dañado/en reparación, visualización, extraviado, on loan y  en pedido.</font>
