<?php
$lnk_crear="Cargar Novedad";
$lnk_buscar="Buscar";
$lnk_listar="Listar";
$lnk_salir="Salir";
$lnk_ver="Detalle...";
$btn_modificar="Modificar";
$btn_eliminar="Borrar";
$btn_seleccionar=">>>";
$btn_guardar="Guardar";
$btn_limpiar="Limpiar";
$btn_cancelar="Cancelar";
$btn_buscar="Buscar";
$btn_listar="Listar";
$msj_browse_no_filas="No existen Novedades.";
$msj_browse_cant_filas="Novedades cargadas.";
$msj_query_browse_cant_filas="Novedades encontradas.";
$msj_listresult_cant_filas="Registros listados.";
$msj_insert="Se ha guardado correctamente.";
$msj_no_insert="No se pudo guardar.";
$msj_insert_repetido="No se puede guardar, ya existe un Tema con esa descripcion.";
$msj_update="Se ha guardado correctamente.";
$msj_no_update="No se pudo guardar.";
$msj_update_repetido="No se puede guardar, ya existe un Tema con esa descripcion.";
$msj_delete_alert_js="Esta seguro que desea eliminar esta novedad?";
$msj_delete="Se ha borrado correctamente.";
$msj_no_delete="No se puede borrar.";
?>